version: '2'
services:
    companysharingexternal-app:
        image: companysharingexternal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://companysharingexternal-mariadb:3306/companysharingexternal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    companysharingexternal-mariadb:
        extends:
            file: mariadb.yml
            service: companysharingexternal-mariadb
