---
path: .
instances: 1
buildpack: https://github.com/cloudfoundry/java-buildpack
services:
- companysharingexternal
applications:
- name: companysharingexternal
  env:
    SPRING_PROFILES_ACTIVE: prod, cloudfoundry
